backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads" # المجلد الذي ستخزن فيه الصور المرفوعة
public_folder: "/images/uploads"

collections:
  - name: "projects"
    label: "Projects"
    folder: "content/projects" # هنا سيتم حفظ بيانات المشاريع كملفات
    create: true
    fields:
      - { label: "Project Title", name: "title", widget: "string" }
      - { label: "Project Image", name: "image", widget: "image" }
      - { label: "Project Description", name: "body", widget: "markdown" }